### ISSUE TITLE
麻烦问下wechatcallkit是否不兼容ios10

### ISSUE THREAD

**Issue by jackiejtr** [JNTian/ShortLook-WeChat#3]
找不到项目发在这里了抱歉。
![image](https://user-images.githubusercontent.com/14011172/43316026-cccbf5f0-91d2-11e8-853e-ed9a00a3ebcc.png)

**Comment by ikanam** [comment]
已经换了压缩方式了，你再尝试一下

**Comment by jackiejtr** [comment]
源内版本还是0.01么 如果是还是报错。。

**Comment by ikanam** [comment]
@jackiejtr 对，还是0.0.1，刷新一下源应该能装了。

**Comment by jackiejtr** [comment]
OK搞定了感谢大佬 QQ的callkit也在开发日程内么？
